add_executable(desktop_test desktop_test.cpp)
target_link_libraries(desktop_test PRIVATE boop_desktop Qt6::Test)
add_test(NAME desktop COMMAND desktop_test)
set_tests_properties(desktop PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
find_program(DBUS_RUN_SESSION dbus-run-session)
if(DBUS_RUN_SESSION)
  add_executable(desktop_dbus_test desktop_dbus_test.cpp)
  target_link_libraries(desktop_dbus_test PRIVATE boop_desktop Qt6::Test)
  add_test(NAME desktop_dbus COMMAND ${DBUS_RUN_SESSION} -- $<TARGET_FILE:desktop_dbus_test>)
endif()
