include(GNUInstallDirs)
install(TARGETS usb-boop RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
install(FILES resources/usb-boop.desktop DESTINATION ${CMAKE_INSTALL_DATADIR}/applications)
install(FILES ../Sources/App/Assets.xcassets/AppIcon.appiconset/icon_256x256.png
        DESTINATION ${CMAKE_INSTALL_DATADIR}/icons/hicolor/256x256/apps RENAME usb-boop.png)
install(FILES ../LICENSE DESTINATION ${CMAKE_INSTALL_DATADIR}/licenses/usb-boop)
set(CPACK_PACKAGE_NAME "usb-boop")
set(CPACK_PACKAGE_VENDOR "alexcatdad")
set(CPACK_PACKAGE_CONTACT "https://github.com/alexcatdad/usb-boop/issues")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Desktop app reporting negotiated USB link speed")
set(CPACK_PACKAGE_VERSION "${USB_BOOP_VERSION}")
set(CPACK_PACKAGE_FILE_NAME "usb-boop-linux-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "qt6-wayland")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_AUTOREQ ON)
set(CPACK_RPM_PACKAGE_REQUIRES "qt6-qtwayland")
set(CPACK_RPM_PACKAGE_RELEASE 1)
set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION /usr/share /usr/share/icons /usr/share/icons/hicolor /usr/share/icons/hicolor/256x256 /usr/share/icons/hicolor/256x256/apps /usr/share/applications /usr/share/licenses)
include(CPack)
